vpc-name      = "Jenkins-Vpc"
igw-name      = "Jenkins-igw"
subnet-name   = "Jenkins-Subnet"
rt-name       = "Jenkins-route-table"
sg-name       = "Jenkins-sg"
instance-name = "Jenkins-Instance"
key-name      = "JK-Key"
iam-role      = "Jenkins-iam-role"
