---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: three-tier
spec: 
  ports:
  - port: 3500
    protocol: TCP
    targetPort: 3500
  type: ClusterIP
  selector:
    app: api
  type: NodePort
