apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
      containers:
      - name: frontend
        image: jprakash1/todoapp-frontend
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://localhost:8080/api/tasks"
        ports:
        - containerPort: 3000
