apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    app: frontend
  
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jprakash1/todoapp-frontend:1.0.0.168
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://localhost:8080/api/tasks"
        ports:
        - containerPort: 3000
               
---
  
apiVersion: v1
kind: Service
metadata: 
  labels:
    app: frontend
  name: frontend
  namespace: three-tier
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
  type: NodePort
